1.5.7 Changes
eclipse-uprotocol/up-python pull request #21
Opened 2024-04-03 20:06 UTC by matthewd0123

* Add Notification UMessageType
* Add isShortForm()
* Various Fixes
* 100% Code Coverage
* Added Linter and Coverage checker to build

2024-04-03 20:13 UTC, matthewd0123 commented
#22

2024-04-04 19:23 UTC, neelam-kushwah requested changes
Bump the version to 0.1.2-dev

2024-04-05 18:04 UTC, neelam-kushwah reviewed
How are you ensuring code coverage? Is there a way we can generate reports similar to what we do in Java? Let's explore this.

2024-04-06 01:12 UTC, neelam-kushwah requested changes

2024-04-06 01:12 UTC, neelam-kushwah commented on uprotocol/uri/factory/uresource_builder.py
> +    def for_rpc_request(method: Union[str, None], id: Union[int, None] = None):
Specifying None in type hints is often redundant as Python allows None by default for any parameter.

2024-04-06 03:11 UTC, neelam-kushwah approved these changes

2024-04-06 03:15 UTC, merged